-- Dialogos production schema for Supabase
-- Run this in Supabase SQL Editor once.

create extension if not exists pgcrypto;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  guest_id text unique not null,
  display_name text,
  email text,
  stripe_customer_id text,
  free_count integer not null default 10,
  credits integer not null default 0,
  subscription_id text,
  subscription_status text,
  subscription_plan text,
  subscription_current_period_end timestamptz,
  subscription_cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  philosopher_id text not null,
  summary text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

-- Typed memory categories are stored in memories.summary as [user_profile_memory],
-- [active_theme_memory], [conversation_state_memory], [philosopher_specific_memory],
-- or [unresolved_questions_memory] for backward compatibility with existing Vercel DBs.
create table if not exists memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id) on delete cascade,
  summary text not null,
  importance integer not null default 1,
  character_related text not null default 'global',
  updated_at timestamptz not null default now()
);

create table if not exists unlocked_characters (
  user_id uuid not null references users(id) on delete cascade,
  character_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, character_id)
);

create table if not exists purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete set null,
  guest_id text not null,
  stripe_session_id text unique not null,
  stripe_customer_id text,
  package_id text not null,
  kind text not null,
  amount_jpy integer not null,
  credits_added integer not null,
  status text not null default 'completed',
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_conversations_user_updated on conversations(user_id, updated_at desc);
create index if not exists idx_messages_conversation_created on messages(conversation_id, created_at desc);
create index if not exists idx_memories_user_importance on memories(user_id, importance desc, updated_at desc);
create index if not exists idx_memories_user_character_updated on memories(user_id, character_related, updated_at desc);
create index if not exists idx_users_guest_id on users(guest_id);
create index if not exists idx_users_stripe_customer on users(stripe_customer_id);
create index if not exists idx_purchases_stripe_session on purchases(stripe_session_id);

-- OTP tokens for email-based account sync
create table if not exists email_otp (
  id bigint generated by default as identity primary key,
  email text not null,
  code text not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_email_otp_email_created on email_otp(email, created_at desc);

-- RLS: enable protection on all app tables.
-- Dialogos does not expose Supabase directly to the browser.
-- Vercel API uses SUPABASE_SERVICE_ROLE_KEY server-side, which bypasses RLS.
-- Therefore no public anon/authenticated policies are created here.
alter table users enable row level security;
alter table conversations enable row level security;
alter table messages enable row level security;
alter table memories enable row level security;
alter table unlocked_characters enable row level security;
alter table purchases enable row level security;
alter table usage_events enable row level security;
alter table email_otp enable row level security;

-- Verification query:
-- select schemaname, tablename, rowsecurity
-- from pg_tables
-- where schemaname = 'public'
--   and tablename in ('users','conversations','messages','memories','unlocked_characters','purchases','usage_events')
-- order by tablename;
